apiVersion: v1
kind: Service
metadata:
  name: search-svc
  labels:
    app: phonebook
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    app: searchserver
  #clusterIP: None