apiVersion: apps/v1
kind: Deployment 
metadata:
  name: web-deploy 
  labels: 
    app: phonebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver   
  template:
    metadata:
      labels:
        app: webserver 
    spec:
      containers:
        - name: clarusway/webserver13
          image: webserver13 
          #env method 1 ve 2 de.
          ports:
          - containerPort: 80

# # Method 3
#           volumeMounts:
#             - mountPath: /config/
#               name: demo-config-volume
#               readOnly: true
#       volumes:
#       - name: demo-config-volume
#         configMap:
#           name: demo-config
#           items:
#           - key: config 
#             path: demo.yaml

#Method 1
          envFrom:
            - configMapRef:
                name: servers-config
          resources:
             memory: "200Mi"
             cpu: "100m"
          limits:
            memory: "750Mi"
            cpu: "750m"
            
          env: 
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: MYSQL_PASSWORD
# Method 2   
          # env:
          #   - name: GREETING 
          #     #value: selam
          #     valueFrom:
          #       configMapKeyRef:
          #         key: greeting 
          #         name: demo-config 