apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deploy
  labels:
    app: phonebook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phonebook
  template:
    metadata:
      labels:
        app: phonebook
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80