apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: phonebook
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: phonebook
    name: mysql
  #clusterIP: None