apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    app: phonebook
spec:
  selector:
    matchLabels:
      app: phonebook
      name: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phonebook
        name: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          - name: MYSQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
        resources: {}
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc