apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    app: phonebook
spec:
  selector:
    matchLabels:
      app: phonebook
      name: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phonebook
        name: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
        envFrom:
          - configMapRef:
               name: mysql-config  # configmapteki tum key-value lari alir.
        # env:
        #   - name: MYSQL_DATABASE
        #     valueFrom:
        #       ConfigMapKeyRef:
        #         name: mysql-config
        #         key: MYSQL_DATABASE
        #   - name: MYSQL_DATABASE_HOST
        #     valueFrom:
        #       ConfigMapKeyRef:
        #         name: mysql-config
        #         key: MYSQL_DATABASE_HOST

        #- name: MYSQL_DATABASE_DB
        #     valueFrom:
        #       ConfigMapKeyRef:
        #         name: mysql-config
        #         key: MYSQL_DATABASE_DB
        resources: {}
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc