apiVersion: v1
kind: ConfigMap 
metadata:
  name: mysql-config
data: 
  MYSQL_DATABASE_HOST: mysql-deploy        # endpoint icin kullanilir. burda kullanilmasi gerekmez aslinda
  MYSQL_DATABASE: phonebook-db
  MYSQL_USER: eguankom
