apiVersion: v1
kind: Secret 
metadata:
  name: mysecret
type: Opaque
data:    # burda stringData yazarsam base64 yerine normal isimleri yazabiliriz. admin ve passwordun kendisini
  MYSQL_ROOT_PASSWORD: MTIzNDU2
  MYSQL_PASSWORD: M24wbS5vdy0K



  