apiVersion: v1
kind: Secret 
metadata:
  name: mysecret
type: Opaque
data:    # burda stringData yazarsam base64 yerine normal isimleri yazabiliriz. admin ve passwordun kendisini
  username: TVlTUUxfUk9PVF9QQVNTV09SRA==
  password: M24wbS5vdy0K